version: "3.8"

services:
  pxe-server:
    build:
      context: .
      dockerfile: Containerfile
    container_name: rpi-pxe-server
    hostname: pxe-server

    # Host networking required for DHCP/PXE to work properly
    network_mode: host

    # Required for NFS-Ganesha to function
    privileged: true

    # Security options for NFS and DHCP
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined

    user: root

    volumes:
      - ./data/tftpboot:/tftpboot:Z
      - ./data/nfs:/nfs:Z
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro,Z
      - ./ganesha.conf:/etc/ganesha/ganesha.conf:ro,Z

    # Restart policy
    restart: unless-stopped

    # Environment variables
    environment:
      - TZ=Europe/Bucharest
      - DNSMASQ_USER=root
